### ISSUE TITLE
grass

### ISSUE THREAD

**Issue by swaggererman** [MianReplicate/Indestructible-Blocks#1]
grass really wants to be indestructible. i have to manually set it to destructible by block id every time i load the world. version is 1.21.3 if that helps.

**Comment by MianReplicate** [comment]
It is important that you send a log. I cannot do anything without a log.

**Comment by swaggererman** [comment]
fuck you and your logs

**Comment by MianReplicate** [comment]
I love you too. Thanks for being very helpful.
